### ISSUE TITLE
Ensure high code coverage (now: 61.63%)

### ISSUE THREAD

**Issue by aik099** [minkphp/SahiClient#15]
Main issue: https://github.com/minkphp/Mink/issues/406

Code Coverage: __61.63%__
![sahiclient_code_coverage](https://f.cloud.github.com/assets/1277526/1677698/3fd793be-5d2c-11e3-9af4-2798e20ba280.png)

**Comment by stof** [comment]
Closing this. We reached 89% at the time of stopping maintenance on SahiDriver, and so on this client too
